title: "Minh Hieu Nguyen"
email: minh-hieu.nguyen@univ-lorraine.fr
description: >-
  Assistant professor in Computer Science at the laboratory LCOMS, University of Lorraine, France
theme: jekyll-theme-minimal
